# Header

menu:
  主页: /
  归档: /archives
  标签: /tags
  分类: /categories
  关于: /about

# SubNav
subnav:
  github: "https://github.com/imzhangmengxin"
  weibo: "http://weibo.com/u/6071436038"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/bemessiah"
  #qq: "#"
  #weixin: "#"
  jianshu: "http://www.jianshu.com/u/5e6921022f13"
  douban: "https://www.douban.com/people/44302274/"
  segmentfault: "https://segmentfault.com/u/messiah163"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:litten225@qq.com"
  facebook: "https://www.facebook.com/zhang.mengxin.16"
  google: "https://plus.google.com/u/0/109786624352426899645"
  twitter: "https://twitter.com/zhangmengxin188"
  linkedin: "https://www.linkedin.com/in/梦欣-张-788766b4/"

  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '求打赏筹钱买服务器～~～'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechat.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /img/favicon.ico

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: 100e5b2badcc46fd937a4600b8dbb2de

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

title_change:
  normal: (つェ⊂)哈哈!欢迎小主再回来!
  leave: 不要离开伦家啦。。。

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  修地球的学长: http://seisman.info/
  生产力大集合: http://xclient.info/
  谷歌镜像: https://bb.qqmmgj.com/

aboutme: 爬行在数据科学道路上的全栈渣渣～～
